### ISSUE TITLE
关于插件发布流程

### ISSUE THREAD

**Issue by CaiHaosen** [halo-sigs/plugin-injection#13]
/kind question
我已经在我的 [fork 仓库（origin）](https://github.com/CaiHaosen/plugin-injection)中成功创建并测试了一个版本 [1.0.0-alpha.2](https://github.com/CaiHaosen/plugin-injection/releases/tag/1.0.0-alpha.2)，这个版本可以正常下载安装使用。
由于我没有直接在[Halo SIGs的代码注入插件](https://github.com/halo-sigs/plugin-injection)发布版本的权限，请问我是应该在 halo-sigs/awesome-halo 仓库提交该插件信息吗

**Comment by guqing** [comment]
已经通过邮件邀请你加入本仓库的 Collaborators，通过后你就可以在此仓库直接创建 release 发布一个版本了见 [Create a new release](https://github.com/halo-sigs/plugin-injection/releases)，创建 release 后不需要手动上传插件的 jar 作为 asserts，actions 运行结束后会自动添加，只需要填写 tag、title、release note 即可
