### ISSUE TITLE
实现代码的全局注入

### ISSUE THREAD

**Issue by CaiHaosen** [halo-sigs/plugin-injection#8]
/kind feature
### 概述
**实现代码`head`和`footer`的全局注入**
目前暂时不增加`注入路径`的判断
### 实现方法
参考[自模型交互](https://docs.halo.run/developer-guide/plugin/api-reference/server/extension-client)调用`listAll`读取所有代码自定义模型，根据[head内容处理扩展点](https://docs.halo.run/developer-guide/plugin/api-reference/server/extension-points/template-head-processor)和[footer内容处理扩展点](https://docs.halo.run/developer-guide/plugin/api-reference/server/extension-points/template-footer-processor)实现代码注入

**Comment by CaiHaosen** [comment]
Hi @guqing 

guqing老师您好，代码的全局注入在实现上并没有问题，但在寻找合适的代码结构上有些疑惑。目前我的想法是创建三个类：
- `HtmlService`：用于与自定义模型交互，获取 htmlInjections。
- `HtmlHeadProcessor `和`HtmlFooterProcessor` ：分别处理不同注入点的代码注入逻辑

但我不确定这种构造是否可行？特别是 HtmlHeadProcessor 和 HtmlFooterProcessor 之间会有大量的重复代码

**Comment by guqing** [comment]
> 但我不确定这种构造是否可行？特别是 HtmlHeadProcessor 和 HtmlFooterProcessor 之间会有大量的重复代码

先实现功能，然后在重构代码，代码是否合理不是一次就能做到最好的，需要在重构中总结，听上去你的组织方式是合理的。

关于你提到的有重复代码的情况可以有以下几种方式来重构
1. 继承：可以将重复的代码抽取到一个公共类中如 AbstractHtmlProcessor 然后 HtmlHeadProcessor 和  HtmlFooterProcessor 继承它
2. 组合：将重复的代码提取到一个独立的类中，然后通过组合的方式来使用这个类
3. 使用函数来抽取重复代码：如 Functional 或子类或自定义的类作为方法参数，通过形如 apply 方法传入参数执行公共逻辑

以上只是罗列了一些常见的处理重复的方法，仅供参考
